- hosts: all
  sudo: yes
  gather_facts: no
  tasks:
    - name: install common packages
      yum: name={{ item }} state=installed
      with_items:
        - python-devel
        - python-setuptools
        - make
        - gcc
        - gcc-c++
        - kernel-devel
      tags: base-packages
    - name: mysql4 download
      get_url: url="http://dbstudy.info/mysql/4.1.25/mysql-4.1.25.tar.gz" dest=/tmp
