- hosts: all
  vars:
    mysql_rpm_url: http://dbstudy.info/mysql/4.1.22/rhel4
  sudo: yes
  gather_facts: yes
  tasks:
    - name: install common packages
      yum: name={{ item }} state=installed
      with_items:
        - python-devel
        - python-setuptools
        - make
        - gcc
        - gcc-c++
        - kernel-devel
      tags: base-packages
    - name: perl install for mysql4
      yum: name={{ item }} state=installed
      with_items:
        - perl
        - perl-DBI
      tags: perl
    - name: install mysql4
      shell: rpm -i {{ item }}
      with_items:
        - "{{ mysql_rpm_url }}/MySQL-devel-standard-4.1.22-0.rhel4.x86_64.rpm"
        - "{{ mysql_rpm_url }}/MySQL-server-standard-4.1.22-0.rhel4.x86_64.rpm"
        - "{{ mysql_rpm_url }}/MySQL-client-standard-4.1.22-0.rhel4.x86_64.rpm"
      tags: mysql4
